spring:
    cloud:
      discovery:
        client:
          simple:
            instances:
              test-service:
                - uri: http://localhost:15000
                  metadata:
                    management.context-path: /actuator
    boot:
      admin:
        ui:
          title: Admin tool
          brand: Admin tool

          external-views:
            - label: "Link 1"
              url: https://google.fr
              order: 1000
            - label: "Link 2"
              url: https://github.com
              order: 2000
        cache:
          max-age: 36000


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


server:
   port: 9000